diagram_id: 63
finite_state_machine_id: 22
name: site_fsm
states:
- id: 9
  label: ContextMenu
  x: 887
  y: 1031
- id: 2
  label: Disable
  x: 760
  y: 468
- id: 7
  label: EditLabel
  x: 600
  y: 934
- id: 8
  label: Move
  x: -69
  y: 861
- id: 1
  label: Ready
  x: 532
  y: 560
- id: 4
  label: Selected1
  x: 214
  y: 566
- id: 5
  label: Selected2
  x: 220
  y: 810
- id: 6
  label: Selected3
  x: 249
  y: 1047
- id: 3
  label: Start
  x: 582
  y: 334
transitions:
- from_state: ContextMenu
  label: onLabelEdit
  to_state: EditLabel
- from_state: ContextMenu
  label: onMouseDown
  to_state: Ready
- from_state: EditLabel
  label: onKeyDown
  to_state: Selected2
- from_state: EditLabel
  label: onMouseDown
  to_state: Ready
- from_state: Move
  label: onMouseUp
  to_state: Selected2
- from_state: Ready
  label: onMouseDown
  to_state: Selected1
- from_state: Selected1
  label: onMouseMove
  to_state: Move
- from_state: Selected1
  label: onMouseUp
  to_state: Selected2
- from_state: Selected2
  label: onKeyDown
  to_state: Ready
- from_state: Selected2
  label: onMouseDown
  to_state: Ready
- from_state: Selected2
  label: onMouseDown
  to_state: Selected3
- from_state: Selected3
  label: onMouseMove
  to_state: Move
- from_state: Selected3
  label: onMouseUp
  to_state: ContextMenu
- from_state: Start
  label: start
  to_state: Ready
