---
- name: Create {{ docker_compose_dir }} directory
  file:
    path: "{{ docker_compose_dir }}"
    state: directory

- name: Create docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
  register: awx_compose_config

- name: Render secrets file
  template:
    src: environment.sh.j2
    dest: "{{ docker_compose_dir }}/environment.sh"

- name: Render application credentials
  template:
    src: credentials.py.j2
    dest: "{{ docker_compose_dir }}/credentials.py"

- name: Render SECRET_KEY file
  copy:
    content: "{{ secret_key }}"
    dest: "{{ docker_compose_dir }}/SECRET_KEY"

- name: Start the containers
  docker_service:
    project_src: "{{ docker_compose_dir }}"
  register: awx_compose_start
    
- name: Update CA trust in awx_web container
  command: docker exec awx_web_1 '/usr/bin/update-ca-trust'
  when: awx_compose_config.changed or awx_compose_start.changed

- name: Update CA trust in awx_task container
  command: docker exec awx_task_1 '/usr/bin/update-ca-trust'
  when: awx_compose_config.changed or awx_compose_start.changed
