- name: Set the Kubernetes Context
  shell: "kubectl config set-context {{ kubernetes_context }}"

- name: Get Namespace Detail
  shell: "kubectl get namespace {{ awx_kubernetes_namespace }}"
  register: namespace_details
  ignore_errors: yes

- name: Create AWX Kubernetes Project
  shell: "kubectl create namespace {{ awx_kubernetes_namespace }}"
  when: namespace_details.rc != 0

- name: Set postgresql service name
  set_fact:
    postgresql_service_name: "{{ awx_kubernetes_namespace }}-postgresql"
  when: "pg_hostname is not defined or pg_hostname == ''"
