channels:
- from_fsm: buttons_fsm
  from_fsm_id: 7
  inbox: ''
  outbox: ''
  to_fsm: button_fsm
  to_fsm_id: 12
  type: ''
- from_fsm: buttons_fsm
  from_fsm_id: 7
  inbox: ''
  outbox: ''
  to_fsm: toolbox_fsm
  to_fsm_id: 14
  type: ''
- from_fsm: details_panel_fsm
  from_fsm_id: 21
  inbox: ''
  outbox: ''
  to_fsm: move_fsm
  to_fsm_id: 3
  type: ''
- from_fsm: device_detail_fsm
  from_fsm_id: 19
  inbox: ''
  outbox: ''
  to_fsm: view_fsm
  to_fsm_id: 2
  type: ''
- from_fsm: group_fsm
  from_fsm_id: 5
  inbox: ''
  outbox: ''
  to_fsm: stream_fsm
  to_fsm_id: 20
  type: ''
- from_fsm: hotkeys_fsm
  from_fsm_id: 1
  inbox: ''
  outbox: ''
  to_fsm: null_fsm
  to_fsm_id: 17
  type: ''
- from_fsm: keybindings_fsm
  from_fsm_id: 18
  inbox: ''
  outbox: ''
  to_fsm: hotkeys_fsm
  to_fsm_id: 1
  type: ''
- from_fsm: link_fsm
  from_fsm_id: 4
  inbox: ''
  outbox: ''
  to_fsm: details_panel_fsm
  to_fsm_id: 21
  type: ''
- from_fsm: mode_fsm
  from_fsm_id: 9
  inbox: ''
  outbox: ''
  to_fsm: time_fsm
  to_fsm_id: 8
  type: ''
- from_fsm: move_fsm
  from_fsm_id: 3
  inbox: ''
  outbox: ''
  to_fsm: device_detail_fsm
  to_fsm_id: 19
  type: ''
- from_fsm: rack_fsm
  from_fsm_id: 6
  inbox: ''
  outbox: ''
  to_fsm: group_fsm
  to_fsm_id: 5
  type: ''
- from_fsm: site_fsm
  from_fsm_id: 22
  inbox: ''
  outbox: ''
  to_fsm: rack_fsm
  to_fsm_id: 6
  type: ''
- from_fsm: stream_fsm
  from_fsm_id: 20
  inbox: ''
  outbox: ''
  to_fsm: link_fsm
  to_fsm_id: 4
  type: ''
- from_fsm: test_fsm
  from_fsm_id: 23
  inbox: ''
  outbox: ''
  to_fsm: mode_fsm
  to_fsm_id: 9
  type: ''
- from_fsm: time_fsm
  from_fsm_id: 8
  inbox: ''
  outbox: ''
  to_fsm: buttons_fsm
  to_fsm_id: 7
  type: ''
- from_fsm: toolbox_fsm
  from_fsm_id: 14
  inbox: ''
  outbox: ''
  to_fsm: site_fsm
  to_fsm_id: 22
  type: ''
- from_fsm: view_fsm
  from_fsm_id: 2
  inbox: ''
  outbox: ''
  to_fsm: keybindings_fsm
  to_fsm_id: 18
  type: ''
diagram_id: 85
fsms:
- id: 12
  name: button_fsm
  x1: -2438
  x2: -3026
  y1: -934
  y2: -1532
- id: 7
  name: buttons_fsm
  x1: -2650
  x2: -2850
  y1: -16
  y2: -619
- id: 21
  name: details_panel_fsm
  x1: 5669
  x2: 5140
  y1: -64
  y2: -521
- id: 19
  name: device_detail_fsm
  x1: 7667
  x2: 7214
  y1: -110
  y2: -562
- id: 5
  name: group_fsm
  x1: 3685
  x2: 2256
  y1: 278
  y2: -906
- id: 1
  name: hotkeys_fsm
  x1: 9692
  x2: 9281
  y1: -124
  y2: -549
- id: 18
  name: keybindings_fsm
  x1: 9223
  x2: 8370
  y1: -71
  y2: -614
- id: 4
  name: link_fsm
  x1: 5080
  x2: 4436
  y1: 154
  y2: -732
- id: 9
  name: mode_fsm
  x1: -3760
  x2: -4453
  y1: 192
  y2: -1439
- id: 3
  name: move_fsm
  x1: 6968
  x2: 5813
  y1: 146
  y2: -935
- id: 17
  name: null_fsm
  x1: 10125
  x2: 9925
  y1: -129
  y2: -543
- id: 6
  name: rack_fsm
  x1: 2214
  x2: 1047
  y1: 127
  y2: -753
- id: 22
  name: site_fsm
  x1: 964
  x2: -190
  y1: 128
  y2: -768
- id: 20
  name: stream_fsm
  x1: 4376
  x2: 3868
  y1: 56
  y2: -643
- id: 23
  name: test_fsm
  x1: -4569
  x2: -5140
  y1: 72
  y2: -863
- id: 8
  name: time_fsm
  x1: -3122
  x2: -3693
  y1: -69
  y2: -553
- id: 14
  name: toolbox_fsm
  x1: -680
  x2: -1722
  y1: 265
  y2: -904
- id: 2
  name: view_fsm
  x1: 8311
  x2: 7734
  y1: -25
  y2: -684
name: diagram
states: []
transitions: []
