---

# The following variables will be set by the runner of this playbook:
# src: /tmp/some/path/private_data_dir
# dest: /tmp/some/path/

- name: Prepare data, dispatch job in isolated environment.
  hosts: all
  gather_facts: false
  vars:
    secret: "{{ lookup('pipe', 'cat ' + src + '/env/ssh_key') }}"

  tasks:

    - name: synchronize job environment with isolated host
      synchronize:
        copy_links: true
        src: "{{src}}"
        dest: "{{dest}}"

    - stat: path="{{src}}/env/ssh_key"
      register: key

    - name: create a named pipe for secret environment data
      command: "mkfifo {{src}}/env/ssh_key"
      when: key.stat.exists

    - name: spawn the playbook
      command: "ansible-runner start {{src}} -p {{playbook}} -i {{ident}}"

    - name: write the secret environment data
      mkfifo:
        content: "{{secret}}"
        path: "{{src}}/env/ssh_key"
      when: key.stat.exists
      no_log: True
