---
awx_web_mem_request: 1
awx_web_cpu_request: 500

awx_task_mem_request: 2
awx_task_cpu_request: 1500

awx_rabbitmq_mem_request: 2
awx_rabbitmq_cpu_request: 500

awx_memcached_mem_request: 1
awx_memcached_cpu_request: 500

rabbitmq_version: "3.7.4"

openshift_pg_emptydir: no
openshift_pg_pvc_name: postgresql
