---

- hosts: all
  gather_facts: false
  roles:
    - { role: image_build }
    - { role: openshift, when: "openshift_host is defined" }
    - { role: local_docker, when: "openshift_host is not defined" }
